# Generated by Django 5.0.3 on 2024-03-30 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=255)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=255)),
                ('ContactName', models.CharField(blank=True, max_length=255, null=True)),
                ('ContactTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('City', models.CharField(blank=True, max_length=255, null=True)),
                ('Region', models.CharField(blank=True, max_length=255, null=True)),
                ('PostalCode', models.CharField(blank=True, max_length=255, null=True)),
                ('Country', models.CharField(blank=True, max_length=255, null=True)),
                ('Phone', models.CharField(blank=True, max_length=255, null=True)),
                ('Fax', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SupplierID', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=255)),
                ('ContactName', models.CharField(max_length=255)),
                ('ContactTitle', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Region', models.CharField(blank=True, max_length=255, null=True)),
                ('PostalCode', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('Fax', models.CharField(blank=True, max_length=255, null=True)),
                ('HomePage', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField()),
                ('RequiredDate', models.DateTimeField()),
                ('ShippedDate', models.DateTimeField(blank=True, null=True)),
                ('ShipVia', models.IntegerField()),
                ('Freight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ShipName', models.CharField(blank=True, max_length=255, null=True)),
                ('ShipAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('ShipCity', models.CharField(blank=True, max_length=255, null=True)),
                ('ShipRegion', models.CharField(blank=True, max_length=255, null=True)),
                ('ShipPostalCode', models.CharField(blank=True, max_length=255, null=True)),
                ('ShipCountry', models.CharField(blank=True, max_length=255, null=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=255)),
                ('QuantityPerUnit', models.CharField(max_length=255)),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UnitsInStock', models.IntegerField()),
                ('UnitsOnOrder', models.IntegerField(default=0)),
                ('ReorderLevel', models.IntegerField(default=0)),
                ('Discontinued', models.BooleanField(default=False)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity', models.IntegerField()),
                ('Discount', models.FloatField()),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
    ]
